### PR TITLE
add support for passing in array of jobs

### PR DESCRIPTION
**Pull request by deadlysyn**
i'm with a customer who wants to pass in specific jobs to target within deployments vs doing them all...so, for example, they could specifically target diego cells vs all of cf.  this is an attempt to add that capability based on advice from @calebwashburn.  i'm sure i've missed something, please provide feedback.  :-)

### CODE REVIEW

**Comment by deadlysyn** [comment]
@lsilvapvt does this seem like a good idea/typical use case, or are we going off the rails?  :-)

**Comment by calebwashburn** [comment]
I think it seems reasonable if you want to configure which jobs to include as part of repave.  For instance I could see some customers wanting to do only Diego cells and others doing all vm types.

**Comment by deadlysyn** [comment]
hmm i probably greatly over-simplified this...  thinking out loud.

if there is just one deployment name (e.g. cf) and a list of jobs (e.g. diego, etc) that should work fine...but what if they pass in multiple deployments.  then the jobs loop would need some extra logic to target multiple sets of jobs across all the specified deployments.

maybe this is best achieved by a readme update, since this is sort of an edge case...or maybe we could  do something funky in the JOBS list like JOBS=a,b,c:d,e,f:etc and then map each colon-delimited list of jobs to the right deployment ("right" just being based on ordering of the DEPLOYMENTS/JOBS lists).

may also be over-thinking this...  thoughts?

**Comment by deadlysyn** [comment]
hi folks, appreciate input before going down a bad path...  is the above an edge case best "documented around" in your opinion (maybe we should just say if you plan to specify a JOBS list then you only provide a single DEPLOYMENT).  that would solve the immediate need for this customer (only roll diego cells within cf deployment) but may not be ideal in all cases.

or should we do something (not right syntax, just thinking out loud) like this in secrets.yml:

```
jobs:
    - deploymentX: a,b,c
    - deploymentY: d,e,f
    - deploymentZ: g
```

then have task.sh work through the list of jobs per deployment?  deploymentX/Y/Z/etc would map to DEPLOYMENTS, and (i suppose) if a list of jobs is not found it would just do all (maintain prior behavior unless specifically overridden).

other implementation ideas?  if we get rough agreement, i'll update the script+readme.  :-)

thanks!

**Comment by lsilvapvt** [comment]
I think it is a fair assumption that customers may want to repave only a set of VMs pre-defined in a list. I'm OK with this PR for the JOBS parameter, however it is incomplete, you are missing the entry for the JOBS parameter in `pipeline.yml`, otherwise `JOBS` env var will always be empty in `task.sh`. Also, please update the main README with the details and usage of the new parameter.
Please resubmit it with those updates at your convenience.

With regards to your question about the `deployments vs jobs` scenario, I would prefer to keep the current code as-is and avoid the complexity of having to represent a matrix of deployments vs jobs in the parameters.
Another reason is, the current implementation supports that scenario in a simplified manner: if you define one pipeline per deployment with the deployment name jobs you want to restart for that deployment, it works. 
One possibility to make the pipeline more robust in that scenario is to change the loop through jobs names and do a check of `if <job-name-from-deployment> is in <list-of-jobs-to-restart> then restart job otherwise go-to-next-job--for-current-deployment`. But I think we should start a separate Issue entry/discussion for this feature request. Thanks.

**Comment by calebwashburn** [comment]
I think this may make sense to split to its own task so it’s explicit.  Repave jobs for a deployment which only talks in a deployment and comma delimited list of jobs, no need to pass Singleton job flag.  This makes this absolutely clear what use case this task is used for and removes conditional logic which can cause room for errors due to mis-configuration.

**Comment by deadlysyn** [comment]
thanks for the input!  going for thinest slice of value...  fixed `pipeline.yml` (added the missed `JOBS` param) and updated the readme to match.

happy to work on additional PRs together for splitting to separate task (still needed/preferred?) and make the jobs loop more robust.

**Comment by lsilvapvt** [comment]
Thanks for the PR @deadlysyn !

**Pull request merged**
